-- กิจกรรมนักศึกษาจาก e-activity (011)
-- surrogate PK + UNIQUE(source, source_ref) ทำให้เพิ่มกิจกรรมด้วยมือได้
-- และ scraper แยกแถว source='manual' โดยไม่เขียนทับกัน
-- คอลัมน์ *_text เก็บข้อความดิบคู่กับค่าที่ parse แล้ว เพราะการแปลง พ.ศ./เดือนไทยอาจผิดและต้องไล่ย้อนกลับได้
-- activity_scrape_runs ทำให้เห็นรอบที่ scrape ล้มเหลว ไม่แสดงข้อมูลเก่าราวกับเป็นข้อมูลสด

BEGIN;

CREATE TABLE IF NOT EXISTS activities (
    activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL DEFAULT 'e-activity', source_ref TEXT NOT NULL,
    activity_code TEXT, title TEXT NOT NULL, organizer TEXT, affiliation TEXT,
    activity_type TEXT, learning_dimension TEXT, target_audience TEXT,
    academic_year TEXT, event_start DATE, event_end DATE, event_dates_text TEXT,
    event_time TEXT, venue TEXT, hours NUMERIC(5,1), hours_text TEXT,
    register_start DATE, register_end DATE, register_dates_text TEXT,
    register_method TEXT, register_status TEXT NOT NULL, status_text TEXT,
    capacity INTEGER, applied INTEGER, phone TEXT, description TEXT, detail_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE, is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    admin_note TEXT, updated_by TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    scraped_at TIMESTAMPTZ, row_hash TEXT,
    UNIQUE (source, source_ref)
);
CREATE INDEX IF NOT EXISTS idx_activities_status ON activities (register_status, is_pinned DESC, register_end);

CREATE TABLE IF NOT EXISTS activity_scrape_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(), finished_at TIMESTAMPTZ,
    status TEXT NOT NULL, http_status INTEGER, bytes INTEGER, rows_found INTEGER,
    rows_inserted INTEGER, rows_updated INTEGER, details_fetched INTEGER,
    error TEXT, triggered_by TEXT
);

COMMIT;
